spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coursera?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF8
    username: root
    password: root
  flyway:
    out-of-order: true
    validate-on-migrate: false
    locations: classpath:/migrations
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  print: true

logging:
  level:
    web: trace
    sql: trace
    org.mybatis: trace
    org.apache.ibatis: trace
    com.young.coursera.com.young.coursera.city.mapper: trace
pagehelper:
  support-methods-arguments: true
  params: pageNum=page;pageSize=pageSize;

