spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coursera?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF8
    username: root
    password: root
  flyway:
    out-of-order: true
    validate-on-migrate: false
    locations: classpath:/migrations
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 2m
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml

logging:
  level:
    web: trace
    sql: trace
    com.young.coursera: trace
pagehelper:
  support-methods-arguments: true
  params: pageNum=page;pageSize=pageSize;

# swagger-ui custom path
springdoc:
  swagger-ui.path: /swagger-ui.html

server:
  port: 8090
