DROP TABLE IF EXISTS city;

CREATE TABLE city (
    `id` SERIAL,
    `name` VARCHAR(64),
    `state` VARCHAR(64),
    `country` VARCHAR(64),
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
);

INSERT INTO city (`name`, `state`, `country`) VALUES
('San Francisco', 'California', 'USA'),
('New York City', 'New York', 'USA'),
('Los Angeles', 'California', 'USA'),
('Chicago', 'Illinois', 'USA'),
('Houston', 'Texas', 'USA'),
('Phoenix', 'Arizona', 'USA'),
('Philadelphia', 'Pennsylvania', 'USA'),
('San Antonio', 'Texas', 'USA'),
('San Diego', 'California', 'USA'),
('Dallas', 'Texas', 'USA'),
('San Jose', 'California', 'USA'),
('Austin', 'Texas', 'USA'),
('Jacksonville', 'Florida', 'USA'),
('Fort Worth', 'Texas', 'USA'),
('Columbus', 'Ohio', 'USA'),
('San Francisco', 'California', 'USA'),
('Charlotte', 'North Carolina', 'USA'),
('Indianapolis', 'Indiana', 'USA'),
('Seattle', 'Washington', 'USA'),
('Denver', 'Colorado', 'USA'),
('Washington D.C.', 'District of Columbia', 'USA'),
('Boston', 'Massachusetts', 'USA'),
('Nashville', 'Tennessee', 'USA'),
('El Paso', 'Texas', 'USA'),
('Detroit', 'Michigan', 'USA'),
('Memphis', 'Tennessee', 'USA'),
('Portland', 'Oregon', 'USA'),
('Oklahoma City', 'Oklahoma', 'USA'),
('Las Vegas', 'Nevada', 'USA'),
('Louisville', 'Kentucky', 'USA'),
('Baltimore', 'Maryland', 'USA'),
('Milwaukee', 'Wisconsin', 'USA'),
('Albuquerque', 'New Mexico', 'USA'),
('Tucson', 'Arizona', 'USA'),
('Fresno', 'California', 'USA'),
('Mesa', 'Arizona', 'USA'),
('Sacramento', 'California', 'USA'),
('Atlanta', 'Georgia', 'USA'),
('Kansas City', 'Missouri', 'USA'),
('Colorado Springs', 'Colorado', 'USA'),
('Miami', 'Florida', 'USA'),
('Raleigh', 'North Carolina', 'USA'),
('Omaha', 'Nebraska', 'USA'),
('Long Beach', 'California', 'USA'),
('Virginia Beach', 'Virginia', 'USA'),
('Oakland', 'California', 'USA'),
('Minneapolis', 'Minnesota', 'USA'),
('Tulsa', 'Oklahoma', 'USA'),
('Wichita', 'Kansas', 'USA'),
('New Orleans', 'Louisiana', 'USA'),
('Arlington', 'Texas', 'USA'),
('Tampa', 'Florida', 'USA'),
('Honolulu', 'Hawaii', 'USA'),
('Aurora', 'Colorado', 'USA'),
('Anaheim', 'California', 'USA'),
('Santa Ana', 'California', 'USA'),
('St. Louis', 'Missouri', 'USA'),
('Pittsburgh', 'Pennsylvania', 'USA'),
('Corpus Christi', 'Texas', 'USA'),
('Riverside', 'California', 'USA'),
('Cincinnati', 'Ohio', 'USA'),
('Lexington', 'Kentucky', 'USA'),
('Anchorage', 'Alaska', 'USA'),
('Stockton', 'California', 'USA'),
('Toledo', 'Ohio', 'USA'),
('Saint Paul', 'Minnesota', 'USA'),
('Newark', 'New Jersey', 'USA'),
('Greensboro', 'North Carolina', 'USA'),
('Buffalo', 'New York', 'USA'),
('Plano', 'Texas', 'USA'),
('Lincoln', 'Nebraska', 'USA'),
('Henderson', 'Nevada', 'USA'),
('Fort Wayne', 'Indiana', 'USA'),
('Jersey City', 'New Jersey', 'USA'),
('St. Petersburg', 'Florida', 'USA'),
('Chula Vista', 'California', 'USA'),
('Norfolk', 'Virginia', 'USA'),
('Orlando', 'Florida', 'USA'),
('Chandler', 'Arizona', 'USA'),
('Laredo', 'Texas', 'USA'),
('Madison', 'Wisconsin', 'USA'),
('Winston-Salem', 'North Carolina', 'USA'),
('Lubbock', 'Texas', 'USA'),
('Baton Rouge', 'Louisiana', 'USA'),
('Durham', 'North Carolina', 'USA'),
('Garland', 'Texas', 'USA'),
('Glendale', 'Arizona', 'USA'),
('Reno', 'Nevada', 'USA'),
('Hialeah', 'Florida', 'USA'),
('Chesapeake', 'Virginia', 'USA'),
('Scottsdale', 'Arizona', 'USA'),
('Irving', 'Texas', 'USA'),
('Fremont', 'California', 'USA');



